version: "3.9"

services:
    backend:
        container_name: pibackend
        build: ./backend
        env_file: secrets.env
        volumes: 
            - ./backend/slackbridge/db.sqlite3:/app/db.sqlite3:z

    frontend:
        container_name: pifrontend
        image: nginx:alpine 
        volumes: 
            - ./frontend/primeinsights/build:/usr/share/nginx/html:z

    proxy:
        container_name: piproxy
        image: nginx:alpine 
        volumes: 
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:z
            - ./proxy/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:z
            - ./proxy/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key:z
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - URL=primeinsights.space
            - VALIDATION=http
            - ONLY_SUBDOMAINS=false #optional
            - STAGING=false #optional
        volumes:
            - ./proxy/config:/config:z
        ports:
            - 443:443
            - 80:80 #optional
        restart: unless-stopped
            