# Generated by Django 4.2.1 on 2023-07-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autopost", "0003_post_created_alter_post_channel_alter_post_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="error",
            field=models.CharField(default="", max_length=500),
        ),
    ]
